### ISSUE TITLE
Great work, I have some suggestions

### ISSUE THREAD

**Issue by puxiao** [sguimmara/hammerhead.gl#1]
**use alias**
In this way, there is no need to use relative paths in the code.

```diff
- import Box3 from "../core/Box3";
+ import Box3 from "@/core/Box3";
```

**use index.ts**

> create `src/core/index.ts` to export all

```diff
- import Box3 from "../core/Box3";
- import Version, { Versioned } from "../core/Version";

+ import { Box3, Version, Versioned } from "@/core;
```

--------

I love three.js,  i am also studying WebGPU.

When I saw your project, I was so excited, I felt like I saw a great project just born.

**Comment by sguimmara** [comment]
Thanks for the suggestion ! I just pushed a commit that uses aliases for both `src`and `examples`, as well as adding `index.ts` files for each directory.
